spring:
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: create-drop
    datasource:
      platform: mysql
      url: jdbc:mysql://localhost:3333?
      username: mytest
      psssword: 1111
      driver-class-name: com.mysql.jdbc.Driver
      validation-query: select 1
